### ISSUE TITLE
(1) Get Omega / Phi / Kappa 

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#10]
- look at Anne's code.

**Comment by jlaura** [comment]
DoD: Trent will show us how this works in the Socket GUI.

**Comment by thareUSGS** [comment]
from socetframesettings.cpp
https://isis.astrogeology.usgs.gov/Object/apps/socetframesettings_8cpp_source.html

00418 // getCamPosOPK converts NAIF SPICE into camera positions (lon, lat, height) and camera attitude
00419 // angles (omega, phi, kappa) understood by SOCET Set.  

which calls SPICE function m2eul_c to return OPK from the rotation matrix.
ftp://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/m2eul_c.html

**Comment by twilson271828** [comment]
The mdis2isd app (which I have placed here:  /work/users/tjwilson/mdis2isd/isis/src/messenger/apps/mdis2isd ) now outputs the (omega/phi/kappa) angles but I need to test it and have it reviewed by someone else. After that, the functionality of the app needs to be placed into a class.

**Comment by jlaura** [comment]
Once this gets pushed into git (tomorrow morning) I am happy to review (an learn a bunch!).
