### ISSUE TITLE
(2) Make mouse work in GXP -- testing board

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/camera_model#114]
DoD: 
* The mouse works 
* Created Wiki Wiki page

**Comment by jlaura** [comment]
@thareUSGS Looks like this should be in a different repo?  If not, feel free to reopen.

**Comment by thareUSGS** [comment]
Sorry - this was test to show off git boards for the GXP group. I thought I
deleted it.

-Trent
