### ISSUE TITLE
(1) SPIKE: How modifiable are the keywords in the ISD?  Are they always fixed and the same or can the developer define the keywords?

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#13]
DoD: Response to this issue.

**Comment by jlaura** [comment]
Can we compare a few camera models to see what keyword changes might look like?

**Comment by ihumphrey-usgs** [comment]
Looking at Pinhole, Pushbroom, will try to find others.

**Comment by helikaon00** [comment]
I've added a wiki page called **Image Support Data (ISD) Keywords**
I can't find any standards on keyword names. I've added a list of example keywords to that page.

**Comment by MarjorieH** [comment]
I reviewed the wiki page and modified it since it listed the internal storage of the ISD keywords as opposed to the ISD keywords themselves.

**Comment by helikaon00** [comment]
Alright, the answer to this spike is:
The keywords are not fixed or standardized as far as I could find.
They are defined by the developer. 
We will need to come up with out own standard for keywords and their storage format. The CSM's we create will need to have their required keywords defined somewhere that users can easily find to help them create the proper ISD file to use our CSM's.
