### ISSUE TITLE
(1) SPIKE: Things we need for an MDIS SET

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#14]
DoD: Wiki Page

What is currently hardcoded?

**Comment by ihumphrey-usgs** [comment]
Upon examining the pinhole.cpp SET, the following features are hard-coded:
plugin loading, plugin selection, ISD generation/loading.

The following list describes in more detail what these features entail:

Plugin Loading
- Specifying the location of the plugin libraries
- Loading the plugins
- Selecting the plugins
- Unloading the plugins

ISD Generation/Loading
- Finding the image
- Extracting ISD from the image

**Comment by ihumphrey-usgs** [comment]
<https://github.com/USGS-Astrogeology/camera_model/wiki/General-SET-Requirements>
