### ISSUE TITLE
(4) MdisSensorModel: create (first) imageToGround

### ISSUE THREAD

**Issue by makaylas** [USGS-Astrogeology/camera_model#29]
fill out the (first) imageToGround in MdisSensorModel

Function Signature:

csm::EcefCoord imageToGround(const csm::ImageCoord &imagePt, double height, double desiredPrecision=0.001, double *achievedPrecision=NULL, csm::WarningList *warnings=NULL) const;

**Comment by jlaura** [comment]
Most of the way there - still have to determine how to get look direction.
