### ISSUE TITLE
(3) MdisSensorModel: create imageToRemoteImagingLocus

### ISSUE THREAD

**Issue by makaylas** [USGS-Astrogeology/camera_model#33]
fill out imageToRemoteImagingLocus in MdisSensorModel

**Comment by ihumphrey-usgs** [comment]
What does the SET do with this method?

**Comment by ihumphrey-usgs** [comment]
It seems like this is essentially returning the sensor's look direction in a body-fixed coordinate system?

**Comment by jlaura** [comment]
Checkout:
https://svn.osgeo.org/ossim/trunk/csm_plugins/src/buckeye/BuckeyeSensorModel.h

**Comment by jlaura** [comment]
Here is the other piece - it looks like the above wraps an existing camera: https://svn.osgeo.org/ossim/trunk/ossim/src/ossim/projection/ossimBuckeyeSensor.cpp

Also interesting - I think (?) these are for game cameras...
