### ISSUE TITLE
(2) MdisSensorModel: create getIlluminationDirection

### ISSUE THREAD

**Issue by makaylas** [USGS-Astrogeology/camera_model#36]
fill out getIlluminationDirection in MdisSensorModel

**Comment by ihumphrey-usgs** [comment]
Conceptually this should not be too difficult, just take the XYZ(body-fixed) - SUN(body-fixed) and normalize to get the illumination direction.

- [ ] How do we get the SUN (body-fixed) coordinates?
- [ ] Does illumination consider light-time aberration?

**Comment by jlaura** [comment]
Spice can get you this information using pxform I believe.  Coordinates in body-fixed, without or without LT correction.

**Comment by twilson271828** [comment]
Look at the function sunDistanceAU in $ISISROOT/src/hayabusa/apps/amicacal/AmicaCalUtils.h.  spkpos_c will get you what you need, but you also need to use spice to calculate the start time (in ephemeris seconds).

**Comment by ihumphrey-usgs** [comment]
@twilson271828 Thanks!

**Comment by ihumphrey-usgs** [comment]
Right now, I've modified the ISD.ipynb to generate the Sun's position in Mercury's body-fixed frame:

```python
target = "SUN"
et = isd['ephemeris_time']
reference_frame = "IAU_MERCURY"
light_time_correction="LT+S"
observer="MERCURY"

# We want to get the Sun's position in Mercury's body-fixed frame at the time the image was taken (et)
target_position, lt = spice.spkpos(
    target, 
    et, 
    reference_frame, 
    light_time_correction, 
    observer
)

print(target_position)

>>> [  -3.16487251e+07  -6.06339075e+07  -3.87294858e+04 ]
```

*It is worth noting that the Sun's position is returned in **km**, so it must be converted to meters at some point (probably when this vector gets put into the ISD?).*

TODO:

- [ ] Put these values into the ISD/json
- [ ] Write a test for getIlluminationDirection()
- [ ] In the SET, convert the illumination direction to photometric angles (e.g. incidence)
- [ ] Write to csv
- [ ] Compare qgis plot of incidence angles with fx f1=cube eq=ina(f1) in qview

**Comment by ihumphrey-usgs** [comment]
Note: only the incidence angles will be calculated in the SET. Emission and phase require the getters for spacecraft position to be implemented in the sensor model.
