### ISSUE TITLE
(2) MdisSensorModel: create getSensorPosition

### ISSUE THREAD

**Issue by makaylas** [USGS-Astrogeology/camera_model#38]
fill out getSensorPosition in MdisSensorModel for the following signatures:

csm::EcefCoord getSensorPosition(const csm::ImageCoord &imagePt) const
csm::EcefCoord getSensorPosition(double time) const

**Comment by ihumphrey-usgs** [comment]
TODO:

- [ ] With this information, the SET can compute emission and phase angles
