### ISSUE TITLE
(2) Write code necessary to compile the MDIS camera.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#5]
Compile the stub. (2SP)

**Comment by twilson271828** [comment]
I have started work on a small application that outputs the Image Support Data (ISD) information from an input cube which has been calibrated/spiced.  This is just the beginning though, and I expect this ticket to be broken up into sub-tickets.

**Comment by jlaura** [comment]
Once we have the code from Trent #10 we can more forward on this ticket.

**Comment by ihumphrey-usgs** [comment]
When trying to create a gtest using the MdisNacSensorModel, it turns out there were some missing methods that needed to implemented in the model (pure virtual Methods in Model and GeometricModel).

This will most likely be put in a PR with a very basic test for MdisNaccSensorModel.
