### ISSUE TITLE
(2) How do we derive off of the CSM? 

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#6]
CSM is abstract.  
Results in a stub. (2SP)

**Comment by ihumphrey-usgs** [comment]
See the built CSM documentation for more details. (file:///work/projects/isis/latest/Pinhole/html/index.html)

Inheritance for CSM compliant sensor models:
_csm::Model <- csm::GeometricModel <- csm::RasterGM <- **CustomSensorModel**_

Inheritance for CSMcompliant plugins:
_csm::Plugin <- **CustomPlugin**_

When creating a sensor model (e.g. MDIS camera model) for use with the CSM API, we need to derive the **csm::RasterGM** class.
 
First, the name of this class must follow the CSM requirements, which are outlined in the CSM TRD **Section 5.6** (http://gwg.nga.mil/documents/csmwg/documents/CSM_TRD_Appendix_C_API_Version_3.0__15_November_2010.pdf). Note that only the sensor name, decimal point, and extension are required, and the optional components may be used to more uniquely identify the model for all CSM models.

W will also need to derive **csm::Plugin**. See the CSM TRD for naming convention (**Section 5.9.8**)

For now, two stub classes can be created:
MdisSensorModel
MdisPlugin

*_These can easily be renamed for uniqueness.

**Comment by ihumphrey-usgs** [comment]
ms2494 - MdisPlugin stubs
ihumphrey-usgs - MdisPluginSensorModel stubs

**Comment by ihumphrey-usgs** [comment]
I believe ms2494 has finished the MdisNacSensorModel stub and has compiled it, and I have finished the MdisPlugin stub and compiled it. 

_Reviewer: we can point you to these files when requested._

Note: should we have a designated place to store files for these tickets so they can be reviewed and pushed?
