### ISSUE TITLE
(1) Create a test for ImageToGround.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#63]
DoD: A test sample line being tested via Jenkins.

**Comment by ihumphrey-usgs** [comment]
A simple test (using MdisNacSensorModel::getModelState) has been put in a PR.

Once the imageToGround PR is merged, the test can be updated to test according to DoD.

**Comment by ihumphrey-usgs** [comment]
MdisNacSensorModelTest has an imageToGround1 test that can be tested via Jenkins.

Note that this will not be testable on Jenkins until the server is updated with a gcc toolchain that supports c++11.
This test will fail locally because the truth is based on ISIS3's XYZ reporting on the image.

**Comment by thareUSGS** [comment]
:smile_cat:
