### ISSUE TITLE
(1) Determine standard ISD names and a naming convention.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#66]
DoD: A wiki page.  

See: https://github.com/USGS-Astrogeology/camera_model/wiki/Image-Support-Data-(ISD)-Keywords

**Comment by ihumphrey-usgs** [comment]
[Preliminary wiki page](https://github.com/USGS-Astrogeology/camera_model/wiki/ISD-Standardized-Keywords)

Please review and edit.

**Comment by MarjorieH** [comment]
:+1: :1st_place_medal:
