### ISSUE TITLE
(2) mdis2isis - cut isis nurse strings and verify values

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#93]
DoD:

-[ ] Verify that ISIS and Python implementation are getting the same answers.
-[ ] Is yes, reproduce Python in ISIS

**Comment by thareUSGS** [comment]
@twilson271828, not to work on just yet but GDAL does have its own PVL parser.
https://trac.osgeo.org/gdal/browser/trunk/gdal/frmts/pds/nasakeywordhandler.cpp

See this for how to grab a value:
https://trac.osgeo.org/gdal/browser/trunk/gdal/frmts/pds/isis3dataset.cpp

e.g.
const char *itype = poDS->GetKeyword( "IsisCube.Core.Pixels.Type" );

393	    /***********   Grab samples lines band ************/
394	    const int nCols = atoi(poDS->GetKeyword("IsisCube.Core.Dimensions.Samples",""));
395	    const int nRows = atoi(poDS->GetKeyword("IsisCube.Core.Dimensions.Lines",""));
396	    const int nBands = atoi(poDS->GetKeyword("IsisCube.Core.Dimensions.Bands",""));
